In [2]:
from torch_geometric.data import Data
import torch

In [3]:
#test

x=torch.tensor([[0],[1],[2]],dtype=torch.float)
edge_index=edge_index = torch.tensor([[0, 1],
                           [1, 0],
                           [1, 2],
                           [2, 1]], dtype=torch.float)
x,edge_index

(tensor([[0.],
         [1.],
         [2.]]),
 tensor([[0., 1.],
         [1., 0.],
         [1., 2.],
         [2., 1.]]))

In [4]:
edge_attr=torch.rand((3,3))
edge_attr

tensor([[0.2895, 0.0277, 0.0801],
        [0.1715, 0.3377, 0.1336],
        [0.2071, 0.5747, 0.0366]])

In [5]:
data = Data(x=x, edge_index=edge_index.t().contiguous(),edge_attr=edge_attr)
print(data.edge_attr)


tensor([[0.2895, 0.0277, 0.0801],
        [0.1715, 0.3377, 0.1336],
        [0.2071, 0.5747, 0.0366]])


In [9]:
with open('./test_data.pt','wb') as f:
    torch.save(data,f)
    


In [10]:
data_test=torch.load("./test_data.pt")
print(data,data.x,data.edge_index,data.edge_attr)

Data(x=[3, 1], edge_index=[2, 4], edge_attr=[3, 3]) tensor([[0.],
        [1.],
        [2.]]) tensor([[0., 1., 1., 2.],
        [1., 0., 2., 1.]]) tensor([[0.2895, 0.0277, 0.0801],
        [0.1715, 0.3377, 0.1336],
        [0.2071, 0.5747, 0.0366]])
